image: lkrawczyk/docker-hugo-npm:0.58.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - deploy

pages:
  stage: deploy
  script:
  - npm install
  - cd site
  - hugo
  artifacts:
    paths:
    - site/public
  only:
  - master

deploy_productive:
  stage: deploy
  script:
    - echo "Deploy to production server not yet implemented for a reason."
  environment:
    name: production
    url: https://panorama-research.org
  when: manual
  only:
  - master
