image: lkrawczyk/docker-hugo-npm:0.58.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build
  - deploy

build:
  stage: build
  script: 
  - npm install
  - cd site
  - hugo
  artifacts:
    when: on_success
    paths:
    - site/public

pages:
  stage: deploy
  script:
  - mkdir public
  - mv site/public public
  artifacts:
    paths:
    - public
  only:
  - master

deploy_productive:
  stage: deploy
  script:
    - echo "Deploy to production server not yet implemented for a reason."
  environment:
    name: production
    url: https://panorama-research.org
  when: manual
  only:
  - master
