image: lkrawczyk/docker-hugo-npm:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
  # Since NPM is a pain in the ...., we need to use this flag to fix an unreported error.
  - npm install --unsafe-perm
  - cd site
  - hugo
  cache:
    policy: push
    paths:
    - node_modules/
  artifacts:
    paths:
    - site/public

pages:
  # Pages is the default staging environment. Anytime something gets committed to the master branch, the staging environment will be updated.
  stage: deploy
  script:
    - echo Updated staging environment on $(date)
    - mkdir public
    - cp -vfR site/public/* public/
  artifacts:
    paths:
    - public
  only:
  - master

deploy_productive:
  # Placeholder for uploading content onto the panorama website.
  stage: deploy
  script:
    - lftp -c "set net:timeout 5; set net:max-retries 2; set net:reconnect-interval-base 5; set ftp:ssl-force yes; set ftp:ssl-protect-data true; open -u $USER,\"$PASS\" $URL; mirror -Rev site/public/ ./www  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  when: manual
  only:
  - master
  artifacts:
    paths:
    - site/public
