# baseurl = "https://panorama-research.org/"
baseurl = "" # Fixes staging build
relativeurls = true # Fixes staging build (bad css)
DefaultContentLanguage = "en"
title = "" 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"
twitter_url = "https://twitter.com/PanoramaEng"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The PANORAMA project boosts design efficiency for heterogeneous automotive and aerospace systems."
  subtitle = ""
  seo_title_suffix = " | Panorama Project"
  keywords = []
  logo = "images/panorama-logo.svg"
  styles = "css/styles.css"
  favicon = "images/panorama-favicon.ico"
# share_img = ""
#gcse = "011805775785170369411:p3ec0igo0qq"
  gcse=""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""
  title = "Our lates news"


#[Params.recent_posts]
#    enable = true
#    title = "Our latest news"
#    subtitle = ""


[taxonomies]
  category = "categories"
  tag = "tags"
  participation_level = "participation_levels"

[Author]
  name = "Panorama Project"
  website = "https://panorama-research.org/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 1

[[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = 3

[[menu.main]]
  name = "Use Cases"
  url = "/usecases/"
  weight = 4

  [[menu.main]]
    name = "Collaboration"
    url = "/usecases/collaboration"
    weight = 4
    parent = "Use Cases"

  [[menu.main]]
    name = "Hardware Assessment"
    url = "/usecases/hardware-assessment"
    weight = 4
    parent = "Use Cases"

  [[menu.main]]
    name = "Deployment Alternatives"
    url = "/usecases/deployment-alternatives"
    weight = 4
    parent = "Use Cases"

  [[menu.main]]
    name = "Guidance"
    url = "/usecases/guidance"
    weight = 4
    parent = "Use Cases"
  
  [[menu.main]]
    name = "Traceability"
    url = "/usecases/traceability"
    weight = 4
    parent = "Use Cases"

  [[menu.main]]
    name = "Security"
    url = "/usecases/security"
    weight = 4
    parent = "Use Cases"
  

[[menu.main]]
  name = "Related Projects"
  url = "/relatedprojects/"
  weight = 7

[[menu.main]]
    name = "Partners"
    url = "/partners/"
    weight = 8

