baseURL = "http://www.panorama-research.org/"
languageCode = "en-us"
title = "Panorama - Boosting Design Efficiency for Heterogeneous Systems"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "../node_modules/"