baseURL = "" # Fixes staging build
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Panorama - Boosting Design Efficiency for Heterogeneous Systems"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
themesDir = "../node_modules/"
enableRobotsTXT = true

[module.hugoVersion]
min = "0.55"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Panorama project boosts design efficiency for heterogeneous automotive and aerospace systems."
  subtitle = "Accelerating design efficiency for automotive and aerospace systems"
  seo_title_suffix = " | ITEA3"
  keywords = ["open-source", "system designs", "heterogeneous systems"]
  logo = "images/logo/logo_panorama.svg"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
  share_img = "images/logo/logo_panorama.svg"
  gcse = ""
#  subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""
  navbar_wrapper_classes = "background-white"

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Panorama Project partners"
  website = "http://www.panorama-research.org"
  email = "info@panorama-research.org"
  #facebook = ""
  twitter = "PanoramaEng"
  #youtube = ""
  #googleplus = ""
  #linkedin = ""

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
#[[menu.main]]
#  name = "About"
#  url = "/about/"
#  weight = 1
